# Site settings
title: Solace JMS API
baseurl: "/solace-samples-jms" # the subpath of your site, e.g. /solace-samples-java
repository: https://github.com/SolaceSamples/solace-samples-jms

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
links-community: http://dev.solace.com/community/
links-get-started: http://dev.solace.com/get-started/jms-tutorials/
links-downloads: http://dev.solace.com/downloads/
links-tech-other: http://dev.solace.com/tech/#other
links-java-tutorial: http://dev.solace.com/get-started/java-tutorials/topic-queue-mapping_java/
docs-vmr-setup: http://docs.solace.com/Solace-VMR-Set-Up/Setting-Up-VMRs.htm
docs-core-concepts: http://docs.solace.com/Features/Core-Concepts.htm
docs-jms-home: http://docs.solace.com/Solace-JMS-API/JMS-home-open.htm
docs-jms-connections: http://docs.solace.com/Solace-JMS-API/Establishing-Connections.htm
docs-gm-rr: http://docs.solace.com/Solace-JMS-API/Using-Topic-Requestors.htm
docs-topic-mapping: http://docs.solace.com/Features/Core-Concepts.htm#topic-queue-mapping
docs-semp: http://docs.solace.com/SEMP/Using-SEMP-to-Manage-and-Monitor-Routers.htm

#----------------------------------------------------
# Generally don't modify items below this point

url: "solacesamples.github.io" # the base hostname & protocol for your site

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  tutorials:
    output: true
    permalink: /:path/
